import { Expose, Type } from 'class-transformer';
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
  MinLength,
} from 'class-validator';
import {
  EligibilityStatus,
  PrescriptionStatus,
} from '../../../common/enums/prescription.enums';

// ── Queue filter ──────────────────────────────────────────────────────────────

export class PrescriberQueueQueryDto {
  /**
   * Default: SUBMITTED — the primary work queue.
   * UNDER_REVIEW returns prescriptions already claimed by this prescriber.
   */
  @IsOptional()
  @IsEnum(PrescriptionStatus)
  status?: PrescriptionStatus;

  /**
   * Filter by eligibility — useful for triaging FAIL cases first.
   */
  @IsOptional()
  @IsEnum(EligibilityStatus)
  eligibilityStatus?: EligibilityStatus;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Type(() => Number)
  page?: number = 1;

  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(50)
  @Type(() => Number)
  limit?: number = 20;
}

// ── Claim (SUBMITTED → UNDER_REVIEW) ──────────────────────────────────────────

/**
 * No body needed — the prescriber ID comes from the JWT.
 * Kept as a named DTO for consistency and future extension.
 */
export class ClaimPrescriptionDto {
  /** Optional note when claiming, e.g. "Taking over from colleague" */
  @IsOptional()
  @IsString()
  @MaxLength(500)
  note?: string;
}

// ── Approve ───────────────────────────────────────────────────────────────────

export class ApprovePrescriptionDto {
  /**
   * Plain-English dosage instructions printed on the dispensing label.
   * e.g. "Take one tablet twice daily with food"
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(1000)
  dosageInstructions: string;

  /**
   * Number of units to dispense.
   * Must match the product's standard pack size or a clinical override.
   */
  @IsInt()
  @Min(1)
  @Max(9999)
  quantityToDispense: number;

  /**
   * Prescription expiry date (ISO 8601).
   * UK legal maximum for most POM prescriptions is 6 months.
   * Enforced by the service layer.
   */
  @IsDateString()
  expiryDate: string;

  /**
   * Optional clinical notes for the dispenser or for the record.
   * NOT shown to the customer.
   */
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  clinicalNote?: string;

  /**
   * When eligibilityStatus is FAIL, a clinical justification is mandatory
   * to override the automatic flag. Enforced by the service layer.
   */
  @IsOptional()
  @IsString()
  @MinLength(20, { message: 'Override justification must be at least 20 characters' })
  @MaxLength(2000)
  eligibilityOverrideJustification?: string;
}

// ── Reject ────────────────────────────────────────────────────────────────────

export class RejectPrescriptionDto {
  /**
   * Clinical reason for rejection — shown to the customer.
   * Must be meaningful; the service rejects single-word reasons.
   */
  @IsString()
  @IsNotEmpty()
  @MinLength(10, { message: 'Rejection reason must be at least 10 characters' })
  @MaxLength(2000)
  reason: string;

  /**
   * Internal clinical note — NOT shown to the customer.
   * Mandatory for FAIL-eligibility rejections.
   */
  @IsOptional()
  @IsString()
  @MaxLength(2000)
  internalNote?: string;
}

// ── Request more info ─────────────────────────────────────────────────────────

export class RequestMoreInfoDto {
  /**
   * Specific information the prescriber needs before they can make a decision.
   * Shown to the customer so they know what to provide.
   */
  @IsString()
  @IsNotEmpty()
  @MinLength(10)
  @MaxLength(2000)
  requestedInformation: string;
}

// ── Response — rich prescription review view ──────────────────────────────────

export class PrescriberPatientSummaryDto {
  @Expose() id: string;
  @Expose() firstName: string;
  @Expose() lastName: string;
  @Expose() dateOfBirth: Date | null;
  @Expose() nhsNumber: string | null;
  /** Previous prescription count for this customer — computed by service */
  @Expose() previousPrescriptionCount: number;
}

export class PrescriberProductSummaryDto {
  @Expose() id: string;
  @Expose() name: string;
  @Expose() medicineType: string;
  @Expose() bnfCode: string | null;
  @Expose() requiresPrescription: boolean;
}

export class PrescriberDocumentDto {
  @Expose() id: string;
  @Expose() documentType: string;
  @Expose() originalFilename: string;
  @Expose() mimeType: string;
  @Expose() scanStatus: string;
  @Expose() uploadedAt: Date;
  /** Pre-signed S3 URL — generated by StorageService, 15 min TTL */
  @Expose() presignedUrl: string | undefined;
}

export class PrescriberReviewResponseDto {
  @Expose() id: string;
  @Expose() status: PrescriptionStatus;
  @Expose() eligibilityStatus: EligibilityStatus | null;
  @Expose() eligibilityNotes: string[] | null;
  @Expose() customerNote: string | null;
  @Expose() prescriberNote: string | null;
  @Expose() submittedAt: Date | null;
  @Expose() reviewedAt: Date | null;
  @Expose() createdAt: Date;

  @Expose()
  @Type(() => PrescriberPatientSummaryDto)
  patient: PrescriberPatientSummaryDto;

  @Expose()
  @Type(() => PrescriberProductSummaryDto)
  product: PrescriberProductSummaryDto;

  @Expose() questionnaireResponse: Record<string, unknown> | null;

  @Expose()
  @Type(() => PrescriberDocumentDto)
  documents: PrescriberDocumentDto[];

  /** Chronological audit trail for this prescription */
  @Expose() auditHistory: Array<{
    action: string;
    actorRole: string | null;
    gphcNumber: string | null;
    metadata: Record<string, unknown> | null;
    createdAt: Date;
  }>;
}

export class PrescriberQueueItemDto {
  @Expose() id: string;
  @Expose() status: PrescriptionStatus;
  @Expose() eligibilityStatus: EligibilityStatus | null;
  @Expose() submittedAt: Date | null;
  @Expose() createdAt: Date;
  @Expose() customerName: string;
  @Expose() productName: string;
  @Expose() medicineType: string;
}

export class PaginatedQueueDto {
  @Expose() data: PrescriberQueueItemDto[];
  @Expose() total: number;
  @Expose() page: number;
  @Expose() limit: number;
  @Expose() totalPages: number;
}
